name: Greetings

on: [issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for helping improving the quality of our shard listing!'
        pr-message: 'Thank you for your contribution and welcome to our project!'
