name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG: true
    steps:
    - uses: actions/checkout@v2
    - name: Check shards
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build xorg-dev libglu1-mesa-dev libalut-dev mesa-common-dev libasound-dev
        sudo apt-get install -y ninja-build xorg-dev libglu1-mesa-dev libalut-dev mesa-common-dev libasound-dev --fix-missing
        pwd
        ls -la
        git clone https://github.com/crossuo/crossuo ../crossuo --depth 1
        cmake -B build -S ../crossuo
        cmake --build build --target shardchk
        ./build/tools/xuoi/shardchk --path shards
    - name: Publish shards
      run: |
        mv shards.cfg ~
        git fetch
        git checkout release
        git config advice.addIgnoredFile true
        mv ~/shards.cfg .
    - uses: stefanzweifel/git-auto-commit-action@v4.1.5
      with:
        branch: release
        file_pattern: ./shards.cfg
        repository: .
        commit_user_name: Publish Bot
        commit_user_email: fungos@gmail.com
        commit_author: Danny Angelo Carminati Grein <fungos@gmail.com>
        commit_message: 'Publish shards'
        commit_options: '--no-verify --signoff --verbose'
